<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Akun extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->authclass->check_isvalidated(base_url().'login');
        $this->load->model('Transaksi_model');
    }

    public function index()
    {
        
        $data = array(
            'barang_dat1' => 'hf'
        );
        $this->template->load('template2','frontend/cart', $data);
    }    
    public function checkout($total,$jmlhari)
    {
        $data = array(
            'jmlhari' => $jmlhari,
            'tgl_kembali' => date("Y-m-d"),
            'tgl_transaksi' => date('Y-m-d', strtotime(' +'.$jmlhari.' day')),
            'status' => 'diproses',
            'total' => $total,
            'id_user' => $this->session->userdata("id"),
        );
        $this->Transaksi_model->insert($data);
        $ida= $this->db->insert_id();
        foreach($this->cart->contents() as $key){
            $data2 = array(
                'nonota' => $ida,
                'id_produk' => $key['id'],
                'nama_produk' => $key['name'],
                'id_kategori' => $key['id_kategori'],
                'harga_sewa' => $key['price'],
                'qty' => $key['qty'],
                'sub_total' => ($key['price']*$key['qty']*$jmlhari),
            );
            $this->Transaksi_model->insert2($data2);
            $this->cart->remove($key['rowid']);
        }
        redirect(site_url('akun/ckt/'.$ida));
    }   
    public function ckt($vlu='')
    {
        $auth_assignment = $this->Transaksi_model->get_by_id($vlu);
        $auth_assignment2 = $this->Transaksi_model->get_by_iddtl($vlu);
        $data = array(
            'tran_data' => $auth_assignment,
            'trandetail_data' => $auth_assignment2
        );
        $this->template->load('cetak','frontend/cekout', $data);
    }  
    public function riwayat($vlu='')
    {
        $auth_assignment = $this->Transaksi_model->get_all1($this->session->userdata("id"));
        $data = array(
            'barang_dat1' => $auth_assignment
        );
        $this->template->load('template2','frontend/riwayat', $data);
    }
}

/* End of file Kategori.php */
/* Location: ./application/controllers/Kategori.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-02-07 01:38:10 */
/* http://harviacode.com */