<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pendaftaran2 extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pendaftaran_model');
        $this->load->library('form_validation');        
	   $this->load->library('datatables');
    }

    public function index()
    {
        $data = array('title'=>'Tujuan 2');
        $this->template->load('template','pendaftaran/pendaftaran_list2', $data);
    } 

    public function json() {
        header('Content-Type: application/json');
        echo $this->Pendaftaran_model->json2();
    }

}

/* End of file Pendaftaran.php */
/* Location: ./application/controllers/Pendaftaran.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-03 11:26:31 */
/* http://harviacode.com */