<?php if (!defined('BASEPATH')) exit('No direct script access allowed');
 
class Pdf {
    
    function __construct() {
        include_once APPPATH . '/third_party/fpdf/fpdf.php';
    }
}


/* End of file pdf.php */
/* Location: ./application/libraries/pdf.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-06-07 01:14:36 */
/* http://harviacode.com */