<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Transaksi_model extends CI_Model
{

    public $table = 'transaksi';
    public $id = 'nonota';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all1($id)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->where('id_user', $id);
        return $this->db->get($this->table)->result();
    }    
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }  
    function get_allp()
    {
        return $this->db->query("SELECT max(total)as total FROM transaksi WHERE status='lunas' OR status='belum kembali'")->row();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_by_iddtl($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get('transaksi_detail')->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('nonota', $q);
	$this->db->or_like('jmlhari', $q);
	$this->db->or_like('tgl_kembali', $q);
	$this->db->or_like('tgl_transaksi', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('total', $q);
	$this->db->or_like('session', $q);
	$this->db->or_like('id_user', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('nonota', $q);
	$this->db->or_like('jmlhari', $q);
	$this->db->or_like('tgl_kembali', $q);
	$this->db->or_like('tgl_transaksi', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('total', $q);
	$this->db->or_like('session', $q);
	$this->db->or_like('id_user', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    function insert2($data)
    {
        $this->db->insert('transaksi_detail', $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Transaksi_model.php */
/* Location: ./application/models/Transaksi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-11-22 10:50:15 */
/* http://harviacode.com */